### ISSUE TITLE
When the Messenger window is inactive, clicking in any in...

### ISSUE THREAD

**Issue by aluxian-huginn** [aluxian/Messenger-for-Desktop#765]
**Description:**
When the Messenger window is inactive, clicking in any input field (either "Type a message" field or "Search for people and groups" field) does not activate the input field, only the window. Another click is required to activate the input field.

It would be OK if upon window activation the message input field would be automatically active, but any way the direct click on the field should work in my opinion.
This is the behaviour that can be seen by clicking on the taskbar button or alt-tabbing into the app.

**Steps to reproduce:**
Make another window active (any other window), click in the type a message input field of the Messenger window, see no cursor blinking.

**App version:**
2.0.1 beta

**OS:**
Windows 10

**Works in WhatsApp Web:**

**Extra:**
Keep up the good work!

**Comment by Daniel543M** [comment]
Yeah this is probably the most annoying issue with this version.  Even more annoying than the right click error thing

**Comment by PrimozR** [comment]
Currently on 2.0.5 beta, this issue persists.

**Comment by PrimozR** [comment]
2.0.6 beta, issue persists.

**Comment by aluxian** [comment]
Fixed in 2.0.7 (will be released soon): I added an item menu `Window > Accept First Click`

**Comment by PrimozR** [comment]
Freshly updated 2.0.9., still the same issue. It works sometimes, but not always. I haven't noticed a pattern as to when or why it sometimes works yet. The Window menu setting has no effect (behaviour is the same in both settings).

**Comment by zdenekvecera** [comment]
Hi, 2.0.9-stable, issue persists.

**Comment by Arvacon** [comment]
I confirm that issue still persists. 
I don't see any difference by enabling the "accept first click" choice. 
You can reproduce this by clicking some times once, or other times twice at another place and then go back to your app.
