### ISSUE TITLE
Remember Window Position and Size & Menu Bar

### ISSUE THREAD

**Issue by Razisdaman** [aluxian/Messenger-for-Desktop#944]
* Operating system: Win10
* Messenger for Desktop version: Latest (Not Beta)

I align my messenger on my second screen, but every time I restart my PC it aligns into the corner as if there's no taskbar on the second screen.

Also, could you disable the menu bar by default, or make it remember that you've disabled it?

**Comment by aluxian** [comment]
Please try the latest version: https://github.com/aluxian/Messenger-for-Desktop/releases

Is this still an issue?

**Comment by Razisdaman** [comment]
Hey,

Unfortunately it hasn’t fixed the issue... Here’s a screenshot: https://gyazo.com/b411b044259d08befa5c22d962d7d0aa

Notice how it’s in line for the top left hand corner where I’ve lined it up against another app, however, it overlaps over onto my other screen on the right-hand side and it also falls down below the taskbar at the bottom.
In other words, I line the app up every time in that corner on my second screen, without the overlaps, but when I restart it, the previous position I saved it in does not fully stay there.

Cheers,
Ryan

**Comment by aluxian** [comment]
Ok, thanks for confirming

**Comment by aluxian** [comment]
I fixed the menu bar in 2.0.7 (will be released soon), it will stay hidden once disabled

**Comment by Razisdaman** [comment]
Sweet!
And dude, thanks for your work, it's great!

________________________________

**Comment by Th3CiB0rG** [comment]
I just updated to 2.0.7-dev and this issue is still there for me. The app keeps getting bigger indefinitely on restarts. I'm pretty sure it gets bigger horizontally as well, because I have it load on start up side by side with Discord and they're always overlapping, although I constantly resize them not to be.

**Comment by Razisdaman** [comment]
Hey man, this problem is still happening, any chance of a fix?

**Comment by aluxian** [comment]
I've been busy with other projects lately and will continue so for a few more weeks. I apologize for the delays.

I'm also waiting for a new code signing certificate, without one I can't release updates.

**Comment by Razisdaman** [comment]
Ahh I see! No worries man! Hope it goes well :)

On 2 Sep 2017 17:46, Alexandru Rosianu <notifications@github.com> wrote:

I've been busy with other projects lately and will continue so for a few more weeks. I apologize for the delays.

I'm also waiting for a new code signing certificate, without one I can't release updates.
